# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='startup',
            new_name='startups',
        ),
    ]
