# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment', models.CharField(max_length=25)),
                ('date_of_birth', models.DateTimeField()),
                ('skills', models.TextField()),
                ('more_about_you', models.TextField()),
            ],
        ),
    ]
