# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='image',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
